server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: default
  # api , config server 통신
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tmax-2-final/mealkit-config
          username: namgonkim
          password: <secret>
          default-label: main
#          uri: file:///Users/namgonkim/Documents/GitHub/mealkit-config
#          username:
#          password:


management:
  endpoints:
    web:
      exposure:
        include: info, health, busrefresh, refresh, metrics
