server:
  port: 8888

spring:
  application:
    name: config-service
  # api , config server 통신
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  cloud:
    config:
      server:
        git:
          uri: file:///Users/namgonkim/Documents/Work/git-local-repo
#          uri: https://github.com/namgonkim/msa-ecommerce-config-tmax
#          username:
#          password:


management:
  endpoints:
    web:
      exposure:
        include: info, health, busrefresh, refresh, metrics
